from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    """Schema for a source with title and URL used by the agent."""

    title: str = Field(description="Title of the source")
    url: str = Field(description="URL of the source")


class AgentResponse(BaseModel):
    """Schema for the agent's response including answer and sources."""

    answer: str = Field(description="Answer generated by the agent")
    sources: List[Source] = Field(
        default_factory=list,
        description="List of sources used by the agent to generate the answer",
    )
